
version: '2'

services:
  a2:
    image: a2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
#remove SINGLE line below when going to PROD
      - "5858"
    links:
      - mongo
      - postgres
      - redis
    environment:
      - PORT: 3000                                                   #In Node, can get Web port with process.env.PORT app.listen(process.env.PORT || 3000);
      - MONGO_URL: mongodb://mongo:27017                             #In Node, can connect to Mongo server with URL:  process.env.MONGO_URL
      - POSTGRES_URL: postgres://docker:pw1234@postgres:5432/docker  #In Node, can get Web port with pg.connect(conString, function(err, client, done) {});
#remove ALL lines below when going to PROD    
      - REMOTE_DEBUGGING  
    volumes :
      - ./:/src


  postgres:      
    image: postgres
    environment:
       - POSTGRES_PASSWORD: pw1234
       - POSTGRES_USER: docker
    #remove ALL lines below when going to PROD
    ports: 
      - "5432"
    mem_limit: 100m

  mongo:
    image: mongo
    #remove ALL lines below when going to PROD
    command: "--smallfiles --logpath=/dev/null"
    mem_limit: 100m
    ports:
     - "27017"

  redis:
    image: redis     